### ISSUE TITLE
insufficient proofs

### ISSUE THREAD

**Issue by mimikadze** [developers-against-repressions/case-212#1006]
> Журналисты, очевидцы и участники акции отмечают, что акция прошла исключительно мирно: не было ни порчи имущества, ни насилия со стороны демонстрантов.

Для принятия решения подписывать петицию или нет не хватает независимых входных данных. При детальном рассмотрении оказывается что обвинение не безосновательно (см. issue #892)

**Comment by Iunusov** [comment]
> > Журналисты, очевидцы и участники акции отмечают, что акция прошла исключительно мирно: не было ни порчи имущества, ни насилия со стороны демонстрантов.
> 
> Для принятия решения подписывать петицию или нет не хватает независимых входных данных. При детальном рассмотрении оказывается что обвинение не безосновательно (см. issue #892)

вас никто и не заставляет

**Comment by alexander-mironov** [comment]
Миш, вот тут его последнее слово на суде и комментарий моего коллеги: https://github.com/developers-against-repressions/case-212/issues/892#issuecomment-533142426

**Comment by gf-mse** [comment]
**TL;DR:** Я бы действовал в предположении, что Иван Подкопаев совершил страшное и распылил свой баллончик. А дальше посмотрел бы на остальные случаи и действовал бы, как сердце подскажет.

**Longread:** Давайте допустим, что это действительно могло привести к давке и последствиям. ( Баллончик в толпе вообще-то -- и правда страшная штука. ) С этим есть одна проблема: то, что делала РГ -- _уже_ провоцировало давку. 
То есть : 
 * (а) усилило ли это событие общественную опасность происходящего -- в данном случае вопрос открытый ; 
 * (б) непонятно, не было ли оно спровоцировано общественно опасными действиями РГ ;  
 * (в) кмк, статистически этот один-единственный случай -- при всей своей серьезности, даже если он был -- имхо не отменяет мирного характера акции в целом.  ( Посмотрите на картинки из Франции и Гонконга для примера. )

Так что -- да, если вы хотите чистого пуризма, Подкопаева можно было бы убрать. Но давайте его, например, в виде исключения помилуем? Особенно -- оглянувшись на действия РГ и принимая во внимание, что этот баллончик, даже если был, к счастью, не нанес никому необратимого вреда ?

**Comment by mimikadze** [comment]
WONTFIX. Людям не нужна правда, нужны эмоции.

**Comment by gf-mse** [comment]
Некоторая публика здесь действительно ведет себя излишне эмоционально.

Тем не менее, imho это пока не повод отказываться от проекта в целом.
