### ISSUE TITLE
Добавьте счетчик, а то непонятно, сколько людей подписали

### ISSUE THREAD

**Issue by okonst** [developers-against-repressions/case-212#1007]

**Comment by waynesayonara** [comment]
Было бы круто, но пока что есть workaround: перейдя к файлу README.md, можно увидеть количество контрибьюторов.

**Comment by vostrosablin** [comment]
контрибьюторов уже в три раза меньше чем имен в READ.me

**Comment by lemenkov** [comment]
Dupe of #446

**Comment by lemenkov** [comment]
Исправили в #1088
