### ISSUE TITLE
Missing link to source from GitHub pages

### ISSUE THREAD

**Issue by kachkaev** [developers-against-repressions/case-212#1078]
There should probably be a link to https://github.com/developers-against-repressions/case-212 from https://developers-against-repressions.github.io/case-212/. Otherwise, people who discover the latter URL first may struggle to find means to sign the letter.

WDYT?

**Comment by lemenkov** [comment]
И, кстати, наоборот бы тоже. Я вот не знал, что это публикуется на GH Pages пока этот тикет не прочитал.

**Comment by loalexandra** [comment]
Вы правы, поправим

**Comment by loalexandra** [comment]
Поправили, спасибо
