### ISSUE TITLE
Унифицировать имена фигурантов в письме

### ISSUE THREAD

**Issue by vostrosablin** [developers-against-repressions/case-212#1148]
Унифицируйте, пожалуйста, формат имен фигурантов дела в тексте, а то глаз режет.
То имя первое, то фамилия

**Comment by vostrosablin** [comment]
Пул реквест:

https://github.com/developers-against-repressions/case-212/pull/1153

**Comment by lemenkov** [comment]
Предложен научный метод в PR #1147.

**Comment by lemenkov** [comment]
Дупликат #553

**Comment by fersel** [comment]
done #784
