### ISSUE TITLE
добавить защиту от изменения истории репозитория

### ISSUE THREAD

**Issue by Vany** [developers-against-repressions/case-212#1218]
Найти решение и реализовать технологию, которая даст уверенность подписавшимся что история мастера не будет изменена. То - есть они подписались именно под тем, что прочитали.

**Comment by Vany** [comment]
Один из вариантов - использовать gpg при коммите и при первом коммите указывать sha3 от текущего readme.MD.

Предлагаю внести это в правила добавления подписи.

**Comment by lemenkov** [comment]
> Найти решение и реализовать технологию, которая даст уверенность подписавшимся что история мастера не будет изменена. То - есть они подписались именно под тем, что прочитали.

Форкните к себе, и сравнивайте с мастером.

**Comment by dmgening** [comment]
Подпиши README.md своим ключом и подпись скопируй себе в файлик. Потом просто проверяй, GPG все до вас придумали

**Comment by wildy** [comment]
Подписанные коммиты.

**Comment by Vany** [comment]
мне нужна возможность доказать, что я ставил подпись не под тем документом, который сейчас находится в репозитории.
Сейчас посмотрим что получится, кажется я нашёл хороший вариант.

**Comment by leinlawun** [comment]
@Vany, у мерж-коммита есть два родителя, один из них отражает состояние ветки, куда мержится, другой состояние ветки, которая мержится. Если изменения, которые мержатся, подписаны PGP-подписью, то доказать подпись конкретного документа довольно просто.

**Comment by khvn26** [comment]
По-моему, проще реализовать возможность отозвать подпись через те же пулл-реквесты. Об изменениях в тексте обращения можно узнавать, подписавшись на события репозитория.

**Comment by lemenkov** [comment]
> Нужно ввести Scrum/Agile! С двухнедельным спринтами! И код ревью - без него никак.

Шутки шутками, но для государства бы не помешало. С issue tracker, тикетами, прогрессом, ответственными, код ревью и т.п.

**Comment by Morgan-iv** [comment]
Учитывая, что у нас сейчас в государстве происходит, вполне можно заняться разработкой какой-то автоматизации для общественных кампаний по репрессиям

**Comment by isnog00d** [comment]
> 
> 
> Учитывая, что у нас сейчас в государстве происходит, вполне можно заняться разработкой какой-то автоматизации для общественных кампаний по репрессиям

угу, они же уже занялись автоматизацией репрессий.

**Comment by Vany** [comment]
Сорян, не знал что именно подписывается в подписанном коммите в гите.
Да, подписи вполне хватает.
Я ж из блокчейна, а не из опенсорса =)
