### ISSUE TITLE
Duplicated lines in Readme.md

### ISSUE THREAD

**Issue by epolyan** [developers-against-repressions/case-212#1252]
722 | Спорыш Семён | Backend Developer, г. Санкт-Петербург
-- | -- | --
723 | Спорыш Семён | Backend Developer, г. Санкт-Петербург

**Comment by lemenkov** [comment]
Исправлено. См. багрепорт #1117.

Так что это дупликат.

**Comment by fersel** [comment]
fixed in #1477

**Comment by lemenkov** [comment]
> fixed in #1477

И наделал новых дупликатов. См. #1698
