### ISSUE TITLE
Зачем нужен процесс с файлами?

### ISSUE THREAD

**Issue by klen** [developers-against-repressions/case-212#1518]
Почему бы просто не создать таблицу с подписями и дать возможность людям добавлять себя через PR?

**Comment by j9JMQETa0f** [comment]
Конфликты, сэр. Так раньше и было.

**Comment by klen** [comment]
Ну ресолв тут вроде простой с атомарными строками, но ок, принято, спасибо.

**Comment by fersel** [comment]
[_PTSD от сотен вручную зарезолвленных конфликтов_]
Непростой :) на самом деле мы искали способ, как сделать это просто, но не нашли. Если таковой существует, поделитесь, пожалуйста. (Просто интересно, возможно мы что-то просто не учли).
