### ISSUE TITLE
Политзаключенные

### ISSUE THREAD

**Issue by Samoed** [developers-against-repressions/case-212#1602]
Добавить в список, тех кто уже получил сроки:
[Кирилл Жуков (3 года)](https://zona.media/news/2019/09/04/zhukov-prigovor)
[Данила Беглец (3 года 2 месяца)](https://zona.media/news/2019/09/03/beglec-prenija)
[Евгений Коваленко (3,5 года)](https://zona.media/news/2019/09/04/kvlnk)

**Comment by lemenkov** [comment]
Так они вроде все есть в списке.
