### ISSUE TITLE
В коммите 88a73a25b4908c024c3aacb98165651e799de574 что-то пошло не так

### ISSUE THREAD

**Issue by lemenkov** [developers-against-repressions/case-212#1698]
Народ, коммит 88a73a25b4908c024c3aacb98165651e799de574 наделал дупликатов подписей. Например, я там теперь дважды (погрепайте по "Леменков"). Может откатить?

**Comment by fersel** [comment]
@Zibx это кстати из-за моржа, из него многие дублируются по подписям с файлами, но в итоге не выходят, т.к. там сет; а эта подпись вышла, т.к. имя-фамилия местами отличаются.

Я сейчас в рамках #1694 пофикшу, видимо.

**Comment by igorkamyshev** [comment]
В #1694 пофиксили.
