### ISSUE TITLE
уточнение кодировки

### ISSUE THREAD

**Issue by gf-mse** [developers-against-repressions/case-212#1886]
Ясно, что все и так знают, что существует только utf-8, но давайте это все-таки уточним ( 68fcfab9fe6a38fd7b9268a9e22ce435e02f0aac ).

**Comment by j9JMQETa0f** [comment]
напомнили того чувака, который упорно хотел сделать уточнение про подписавшихся :(

**Comment by gf-mse** [comment]
Снимается по [comment-533529062 в #1873](https://github.com/developers-against-repressions/case-212/pull/1873/#issuecomment-533529062)
