### ISSUE TITLE
косметические изменения кода

### ISSUE THREAD

**Issue by gf-mse** [developers-against-repressions/case-212#1890]
Не настаиваю -- но мне кажется, так это проще читать :
 * e7053535e3491f13667ffc5d5bb42a42e39b6b1e
 * 6614d5709a27ae934c7b4d9445ba27208a12961c

**Comment by SSNikolaevich** [comment]
Не является ли избыточным преобразование sorted_set в list при передаче в sorted в 58 строке?

**Comment by gf-mse** [comment]
@SSNikolaevich 
( Смотрит в код ) .. вы чертовски правы )

То есть [`sorted()` использует `__iter__` объекта](https://github.com/python/cpython/blob/8b03f943c37e07fb2394acdcfacd066647f9b1fd/Python/bltinmodule.c#L2219), и лишний список, действительно, приведет к лишней копии )

ps. я тут руководствовался принципом "Explicit is better than implicit" ( PEP 20, verse 2 ) и, очевидно, был неправ ))

pps. про тесты :  "Pull requests are welcome" (ц) :wink:

**Comment by gf-mse** [comment]
* 6614d5709a27ae934c7b4d9445ba27208a12961c `->` a026e632a23077b735a36749385108f2a4acff46

**Comment by fersel** [comment]
#1873 merged

**Comment by gf-mse** [comment]
Предлагаю закрыть )
