### ISSUE TITLE
Протест который мы заслужили

### ISSUE THREAD

**Issue by slayer** [developers-against-repressions/case-212#1915]
вот теперь власти точно испугаются

**Comment by andyrusinov** [comment]
Такие штуки делаются не для того, чтобы "напугать". Теоретически это средство обратной связи... практически же оно работает только тогда, когда другая сторона готова получать обратную связь. Увы.

**Comment by gf-mse** [comment]
Никаких "увы". Молчание -- знак согласия, что в жизни, что в ОС Unix ; тот же судья Криворучко может искренне считать, что в принципе все в порядке. У нас на сегодня минимальная задача -- сообщить, что это далеко не "в порядке". Я не вижу, почему этим не стоит заниматься.

**Comment by j9JMQETa0f** [comment]
Активизм в России — это крайняя степень отчаяния, граничащая с истерикой. Если же взглянуть на происходящее спокойно, то ясно, что к лучшему положение изменится не раньше, чем через два-три-четыре поколения, когда у власти не останется ни одного потомка партийно-советской номенклатуры и уже столь же потомственных бандитов в погонах и без.

**Comment by gf-mse** [comment]
Тысяча извинений, но давайте придерживаться конкретики. ( Имхо это вообще единственный шанс что-нибудь сделать. ) Есть конкретное предложение. Согласным с предложением предлагается подписываться. Несогласным предлагается приложить замечания по исправлению. ( Совсем несогласным предлагается его игнорировать и заняться чем-нибудь другим на выбор. )

**Comment by gf-mse** [comment]
nb. Это следующий ( возможно, последний ) кандидат на закрытие темы, имхо ))
