### ISSUE TITLE
Опубликовать на GH Pages

### ISSUE THREAD

**Issue by lex111** [developers-against-repressions/case-212#196]
В настройках репозитория выбрать master, появится ссылка только на отрендеренный файл README.MD. Намного лучше, не будет виден интерфейс гитхаба.

![image](https://user-images.githubusercontent.com/4408379/65173092-d1002100-da56-11e9-9d95-71faf9673f06.png)

Сделайте, пожалуйста, @loalexandra

**Comment by mikechip** [comment]
+1

Заодно это делает ссылку короче для публикации на других ресурсах

**Comment by loalexandra** [comment]
Скоро сделаем, спасибо

**Comment by j9JMQETa0f** [comment]
Какой смысл в этом? Я бы не делал этого, смысла нет. Все кто хотел, уже опубликовал, там два-три издания, остальные не впишутся, хайп прошёл!

**Comment by loalexandra** [comment]
https://developers-against-repressions.github.io/case-212/

**Comment by Iunusov** [comment]
> Какой смысл в этом? Я бы не делал этого, смысла нет. Все кто хотел, уже опубликовал, там два-три издания, остальные не впишутся, хайп прошёл!

кремлебот
