### ISSUE TITLE
Инструкция как быстро и правильно подписаться

### ISSUE THREAD

**Issue by papandreus1** [developers-against-repressions/case-212#2029]
Добавьте пожалуйста, простую инструкции по шагам, что сделать
Не все люди опытные и работают с Гитхабом.  Далеко не все знают, что надо делать fork, потом PR.

Например, я сначала сделал коммит на мастер, при push ошибка, нет прав
потом сделал свой бранч в репозитории developers-against-repressions/case-212, при пуше тоже был послан.

Нужна простая инструкция - 1,2,3 все

С уважением,Андрей

**Comment by Alveona** [comment]
Кажется, самый простой способ - зайти в /signed и нажать "Create new file", github сам форкнет и потом предложит сделать пр

**Comment by iurev** [comment]
```
1. Если нет аккаунта на github – зарегаться
2. Перейти по ссылке https://github.com/developers-against-repressions/case-212/new/master/signed
3. В “Name your file” – введите любой набор букв/цифр
4. В контент – по шаблону “Имя Фамилия | Компания, должность”
5. Внизу зеленую кнопку “Propose new file”
6. Откроется новая страница, на ней нужно нажать кнопку “Create pull request”

Также: если появится кнопка "Fork this repository" – ее тоже нужно нажать. Она зеленая
```

По этой инструкции смогли подписаться неразработчики

**Comment by gf-mse** [comment]
ну тогда пошли на change.org. по-моему, весь смысл размещения проекта на github -- это некоторый тест на профессию.

**Comment by gf-mse** [comment]
> Добавьте пожалуйста, простую инструкции по шагам, что сделать
> Не все люди опытные и работают с Гитхабом. Далеко не все знают, что надо делать fork, потом PR.
> 
> Например, я сначала сделал коммит на мастер, при push ошибка, нет прав
> потом сделал свой бранч в репозитории developers-against-repressions/case-212, при пуше тоже был послан.
> 
> Нужна простая инструкция - 1,2,3 все
> 
> С уважением,Андрей
@papandreus1 Андрей, [вот это](https://guides.github.com/activities/hello-world/) не поможет?

**Comment by papandreus1** [comment]
Большое спасибо всем участвовавшим!
