### ISSUE TITLE
Боты

### ISSUE THREAD

**Issue by Iunusov** [developers-against-repressions/case-212#2225]
Мне интересно, что это, кража аккаунта, или это один и тот же человек?
https://github.com/vatobot

Просто если взять его емайл отсюда:
https://github.com/js-org/js.org/commit/a297f94054c6d66d291099cc24f88c7d9cbd0769.patch

и поискать здесь:
https://yandex.ru/search/touch/?text=%22lexrulezzz%40mail.ru%22&lr=177&mda=0

то мы найдем следующие ссылки:
https://id.pr-cy.ru/user/profile/lex111/#/profile
https://leanpub.com/u/lex111
https://github.com/lex111

Но если судить по комментариям, то это разные люди. Кто-то взломал чей-то старый аккаунт, и теперь развлекается? @lex111, @vatobot, есть мысли на этот счёт?))

**Comment by lex111** [comment]
Это мой старый аккаунт, взломали на этой неделе почту на майл.ру, на котором зарегистрирован аккаунт. Пароль поменял, теперь ничего не напишет уже, кто бы это ни был! 

Товарищи, ставьте обязательно **двухфакторную авторизацию**, это действительно важно!
Прощу прощения, не всё прочитал, но это действительно мерзко, спасибо за расследование, @Iunusov! Неизвестно, что он ещё понаписал, никаких оповещений нет (хотя должны вроде быть же?), поэтому считаю лучшим решением удалить аккаунт.

**Comment by Iunusov** [comment]
@lex111, рад, что все прояснилось)
