### ISSUE TITLE
Треть подписавших ждёт своей очереди в пулл реквестах

### ISSUE THREAD

**Issue by Zibx** [developers-against-repressions/case-212#289]
Прогнозирую что сарафанное радио сейчас даст геометрическую прогрессию. 

Нужен либо автоматизированный мёрдж:
Проверка следующих правил: один аккаунт делает только один реквест, в реквесте происходит только добавление одной строки в таблицу.

Либо назначать по одному новому мёрджеру каждые x (например, 50) записей.

**Comment by hom3chuk** [comment]
Готов помочь с мерджами

**Comment by lex111** [comment]
Это же айти - пинг очень высокий :smile:, поэтому нужно набраться терпения.

**Comment by hom3chuk** [comment]
@loalexandra стоило меншнуть, наверное, в уведомлениях от PRов, наверное, адок

**Comment by loalexandra** [comment]
Хотелось бы поспать. Кто-нибудь готов померджить/порешать конфликты?

**Comment by lex111** [comment]
давайте мне

**Comment by treblereel** [comment]
ага, и куча PR в README.md ... ну и все в конфликтах

**Comment by monich** [comment]
Предлагаю имя файла в пулл реквесте - MD5 хэш содержимого.

**Comment by loalexandra** [comment]
Кто хочет фиксить/мержить, напишите в телеграм мне - perlmutter

**Comment by Zibx** [comment]
Итак, был написал краулер. Сейчас все ребята спят, а как проснутся — всё обновят.
Вот репа https://github.com/Zibx/MORJ
