### ISSUE TITLE
Убрать один из способов подписаться

### ISSUE THREAD

**Issue by fylmr** [developers-against-repressions/case-212#302]
![image](https://user-images.githubusercontent.com/24548798/65180254-bdf04f80-da5c-11e9-9e53-835a5a132117.png)

Сейчас в ридми-файле предлагаются два способа подписаться. Пулл реквесты люди тоже делают, используя рандомно какой-то из этих способов. Предлагаю один из них убрать.

**Comment by ERuban** [comment]
а кто-то использует оба способа)

**Comment by lex111** [comment]
Одного было бы достаточно, второй замудренный слишком :thinking:

**Comment by fylmr** [comment]
Я так понимаю, там специально для второго способа [написан скрипт](https://github.com/developers-against-repressions/case-212/blob/master/update_readme.py), так что, видимо, предпочтительнее второй

**Comment by lex111** [comment]
Да, это понятно, но замудренный с точки зрения подписанта (создать файл, назвать его как-то). Мелочи, но всё же.

**Comment by SSNikolaevich** [comment]
Способ с созданием файла сделан, скорее всего, чтобы избежать конфликтов при слиянии изменений из pull request-ов.

**Comment by lex111** [comment]
Так и есть, но тогда нужно было CI прикрутить, в принципе я создал соответствующий пулреквест https://github.com/developers-against-repressions/case-212/pull/244 может быть доберутся до него.

**Comment by loalexandra** [comment]
Спасибо, убрала

**Comment by lemenkov** [comment]
> Да, это понятно, но замудренный с точки зрения подписанта (создать файл, назвать его как-то). Мелочи, но всё же.

Это же для айти-специалиста. Не умеешь пользоваться git, то пока проходи мимо. Как то так, по-моему.

**Comment by j9JMQETa0f** [comment]
@lemenkov вы это 1С-программистам скажите! Явная ничем не прикрытая дискриминация!
