### ISSUE TITLE
Добавить английскую версию

### ISSUE THREAD

**Issue by notpushkin** [developers-against-repressions/case-212#322]
Вполне вероятно, что дело вызовет резонанс и в остальной части интернета (как, например, [996.ICU](https://github.com/996icu/)).

**Comment by fancywriter** [comment]
https://github.com/developers-against-repressions/case-212/pull/429 для начала?

**Comment by doppelex** [comment]
А смысл? Запад нас спасет? Это локальная история, сколько шуму бы не было, посмотрите на список подписантов, там в основном москва и спб, всем остальным до фени на это всё. Почитайте козулю, даже он не стал в этом всём участвовать!

**Comment by espdev** [comment]
> Почитайте козулю, даже он не стал в этом всём участвовать!

Кто такой козуля и почему надо его читать? Его мнение по этому вопросу так важно?

**Comment by j9JMQETa0f** [comment]
Он самый известный айтишник в твиттере, как минимум, директор сбертеха, между прочим! Интересно, а люди, которые поставили мне дизлайк, могут ответить на вопрос в задизлайканном сообщении? Или не способны на это?

**Comment by fcFn** [comment]
Перевёл. Посмотрите, пожалуйста. Если это нужно, и выглядит нормально, я создам PR.

**Comment by pavelzamyatin** [comment]
> Он самый известный айтишник в твиттере
Смелое утверждение. Конечно, пруфы спрашивать бесполезно?
> Интересно, а люди, которые поставили мне дизлайк, могут ответить на вопрос в задизлайканном сообщении?
Я не ставил вам дизлайк (хотя какое это имеет значение?), но тем не менее попытаюсь ответить. 
Смысл перевода на английский хотя бы в том, что это поможет добавить огласки тому, что в России существует мнение отличное от позиции власти. Для многих за рубежом это к сожалению не очевидно. Плюс многие не против распространить данную информацию среди коллег/знакомых, которые тоже не против были бы подписаться.

**Comment by newaccountmine** [comment]
Ничего подобного. За пределами России очень даже следят, и готовы подписать. Например Я!!!

**Comment by j9JMQETa0f** [comment]
Ну вроде Ксения Собчак на так называемых выборах в 2019 года говорила им, что россия это не путин, и что? мне кажется они не такие тупые, что это без всего этого понимать, но в итоге вы такие соучастники всех преступлений, которые ведет этот режим.
Тут коллеги по Лахте-2 сказали, что авторка - несостоявшийся депутка, так почему она не создала аналогичное письмо против недавних выборов? Или то что в россии проводятся нечестные выборы - западу давно известно? Странно подписывать письмо такое письмо от "политика", тем более когда у "нее отняли мандат", это к тому, что ваши "подписи" будут использованы против вас потом.

**Comment by koda85** [comment]
> посмотрите на список подписантов, там в основном москва и спб, всем остальным до фени 
Я с ХМАО и мне не пофиг

**Comment by fancywriter** [comment]
@j9JMQETa0f вы неправильно понимаете смысл всего действия. Дело не в том, что "добрый сильный дядя придёт и поможет наказать отца-алкоголика, который бьёт детей", а в том, что "отец-алкоголик" реально боится огласки. Нет, детей бить ему не стыдно, но "перед пацанами" ему стыдно, такое вот извращённое мировоззрение. Надеюсь, метафора удачная.

**Comment by j9JMQETa0f** [comment]
Вот как раз всё будет по первому сценарию, "царь хороший, бояре плохие", и так уже много лет вами манипулируют, но вы ведетесь, как в первый раз и искреннее верите, что вот это всё как-то поможет и окажет реальный эффект.
ПЫСЫ. Ну хоть кто-то с гитом познакомился, а у некоторых активность на гитхабе прибавилась, уже хорошо! :laughing:

**Comment by fancywriter** [comment]
> у некоторых активность на гитхабе прибавилась
:smile:  :+1:

**Comment by amazing-space-invader** [comment]
> но вы ведетесь, как в первый раз и искреннее верите, что вот это всё как-то поможет и окажет реальный эффект.

Единственное, что нужно для триумфа зла, это чтобы хорошие люди ничего не делали.

**Comment by j9JMQETa0f** [comment]
Отличная и точная цитата к этой ситуации, как заметили другие, даже лоялисты возмутились, но сути дела не меняет, к сожалению.

**Comment by Iunusov** [comment]
> Он самый известный айтишник в твиттере, как минимум, директор сбертеха, между прочим! Интересно, а люди, которые поставили мне дизлайк, могут ответить на вопрос в задизлайканном сообщении? Или не способны на это?

я готов ответить, пиши в личку

**Comment by allan-walpy** [comment]
на акции протеста уже обращали внимание западные СМИ
[например гугл в помощь](https://www.google.com/search?q=moscow+protests)
Были и Independant, The Times, BBC
Думаю объективная картина более ценна, чем мнение каких-то людей в интернете и их авторита или то, что я хочу сказать: "английская версия ничуть не помешает и, возможно, будет полезной"
