### ISSUE TITLE
Привести список фигурантов к единому формату

### ISSUE THREAD

**Issue by pavelzamyatin** [developers-against-repressions/case-212#553]
Собственно, как насчет:
1. Привести список к единому формату "Фамилия Имя"
2. Отсортировать по алфавиту, чтобы не было вопросов, по какому принципу он составлен.

ps. Разумеется, я бы мог создать pull request, но боюсь на данном этапе он потонет в потоке остальных.

**Comment by nazarov-tech** [comment]
I can see the issues with that idea (starting from the idea that certain people including me would not want the ex-ussr order "last name, first name") and the issues with the implementation, but I can't quite see the benefits of it.

Could you elaborate on how and why?

**Comment by pavelzamyatin** [comment]
@nazarov-tech 
Я не совсем понимаю, в чем вы видите проблему. Определенным людям всегда что-то не нравится, это нормально. Я лишь за единообразие. Ок, вам не нравится вариант Фамилия-Имя (что мало отношения имеет к ex-USSR как таковому, но это не суть). Пусть будет Имя-Фамилия. 

Суть в том, что список должен быть консистентным - так его проще читать, не спотыкаясь взглядом о смену порядка.

**Comment by dbl0null** [comment]
Сделал PR:
https://github.com/developers-against-repressions/case-212/pull/1147

**Comment by dbl0null** [comment]
dear @nazarov-tech
maybe this idea is just not that bad?

since no parts from your intentionally European styled transliterated "Dmitry Nazaroff" can be found among normal Russian names - it would not be changed and will be passed as is

cool jacket btw 🥇

**Comment by dbl0null** [comment]
Насчет сортировки по алфавиту - мне кажется было бы справедливо сортировать по порядку поступления подписей. Боюсь только что это уже едва ли возможно. Однако нынешняя ситуация с сортировкой по погоде на марсе (именам файлов?) конечно выглядит несколько несерьезно.

**Comment by loalexandra** [comment]
Список фигурантов привели к одному формату, а список подписавшихся не стали. Думаем, справедливо оставить подписи именно в том виде, в котором их оставили подписанты. 

Всем спасибо за участие.
