### ISSUE TITLE
Че по деньгам?

### ISSUE THREAD

**Issue by soshnikov** [developers-against-repressions/case-212#555]
Сколько вам заплатили? Если чо по чем нынче? Кому продаться, так чтобы не накладно и чтобы не заморачиваться особо?
Поделись опытом, чувак, не жмоться.

**Comment by ruschecker** [comment]
Вы правда думаете, что работнику IT сектора платят зароботную плату недостаточную, чтобы искать такого рода доход?

**Comment by hookzof** [comment]
Платят в самой стабильной валюте – тугриках.

**Comment by lemenkov** [comment]
> Сколько вам заплатили? Если чо по чем нынче? Кому продаться, так чтобы не накладно и чтобы не заморачиваться особо?
> Поделись опытом, чувак, не жмоться.

Надо в АП идти, писать про то, как все хорошо, и т.п. Некоторые так сделали, и живут норм.
