### ISSUE TITLE
Лицензия / права на распространение

### ISSUE THREAD

**Issue by vazhnov** [developers-against-repressions/case-212#620]
Укажите, пожалуйста, лицензию на контент.

**Comment by vazhnov** [comment]
Предполагаю, что тут будет уместна [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by KlonD90** [comment]
WTFPL же

**Comment by lemenkov** [comment]
> WTFPL же

Это особенно плохая лицензия. В данном конкретном случае довольно понятно, что не все подписавшиеся могут захотеть, чтобы их подписи использовались на условиях "Do What The Freak You Want To".

Вообще, как мне кажется, учитывая, что пользователи выкладывают тут свои персданные, выбор лицензий невелик, и это не пермиссивные лицензии, скорее всего.

**Comment by edwardspec** [comment]
> учитывая, что пользователи выкладывают тут свои персданные, выбор лицензий невелик

К списку имён авторское право неприменимо, такой список - это public domain.

Лицензия имеет смысл для текста заявления и скриптов.
