### ISSUE TITLE
Click "Star" to sign

### ISSUE THREAD

**Issue by viatcheslavmogilevsky** [developers-against-repressions/case-212#651]

**Comment by viatcheslavmogilevsky** [comment]
Не проще ли формировать список по "старгейзерам"?

**Comment by TeaTracer** [comment]
Нужно, чтобы это было более осознанно, поставить звёздочку слишком просто, плюс это стандартный интерфейс для другого действия, что может ввести в заблуждение тех, кто хочет подписаться.
