### ISSUE TITLE
добавлять ссылки на github profile?

### ISSUE THREAD

**Issue by tandav** [developers-against-repressions/case-212#653]
Сейчас в таблице имя и фамилия, можно ли делать в формате ?

```md
[Имя Фамилия](https://github.com/username)
```

**Comment by j9JMQETa0f** [comment]
Да. пожалуйста, облечте жизнь эйчарам, а то непонятно просто по имени и фамилии, отказывать ли кандидату или нет.

**Comment by tandav** [comment]
А что если HR умеют в git blame?

**Comment by edwardspec** [comment]
Чем добавлять их вручную, проще поправить update_readme.py, чтобы они добавлялись автоматически. (первый автор git-истории файла в signed/)

**Comment by Zibx** [comment]
Многие добавляют несколько человек одновременно и для составления списка профилей понадобится ввести отдельный столбец и попросить всех создавать пулл реквесты заново, а потом заново всё мёржить. Ну и в профилях нет смысла, как написали выше — это поможет только HR, тут же даже личных сообщений нету.
