### ISSUE TITLE
Read.me таблица обновлется?

### ISSUE THREAD

**Issue by vostrosablin** [developers-against-repressions/case-212#803]
Кажется достаточно много подписавшихся так и не появились в таблице

**Comment by j9JMQETa0f** [comment]
Травис не подключен, @loalexandra видимо все равно.

**Comment by TiGR** [comment]
Подписи лежат в папке signed (там больше 400 файлов), так и не импортированы в ридми.

**Comment by j9JMQETa0f** [comment]
https://github.com/developers-against-repressions/case-212/blob/master/.travis.yml

Нужно просто добавить проект с Travis.

**Comment by loalexandra** [comment]
Скоро будет большой пулл реквест с обновлением ридми, да

**Comment by j9JMQETa0f** [comment]
Просто включите тревис плз

**Comment by TiGR** [comment]
@j9JMQETa0f Каким образом это поможет? Скрипт же не производит никакой фиксации изменений.

**Comment by lemenkov** [comment]
> @j9JMQETa0f Каким образом это поможет? Скрипт же не производит никакой фиксации изменений.

Ну, как минимум, это хороший старт. Например, будет видно, что формат неправильный и мерджить не надо. Дальше уже можно добавить проверок и автогенерилку.

**Comment by j9JMQETa0f** [comment]
@TiGR сорян, не заметил, фронтендеры, что с них взять. не осилили дописать пуш изменений.

**Comment by NMVikings** [comment]
> Просто включите тревис плз

Просто включив тревис перезатрутся все записавшиеся руками в README.md.

По-хорошему нужно вынести всех записанных в README.md в отдельный файл и его тоже читать, плюс в скрипте подписи собирать не в списк, а в сет, чтобы не было повторов.

**Comment by j9JMQETa0f** [comment]
> Просто включив тревис перезатрутся все записавшиеся руками в README.md.

Теперь-то да, но решается выносом в отдельный файл. Это не мое решение, но вроде так это работает, как я понял. Если честно, по-хорошему оставили бы всё есть, и просто пригласили больше мейнтейнеров, которые принимали бы пулреквесты, косяк организации я вижу.

**Comment by yutkin** [comment]
Что с README? Есть обновления?

**Comment by j9JMQETa0f** [comment]
тем более все кто мог, уже написал об этом, лучше сходить на митинг, кто в мск.

**Comment by Iunusov** [comment]
> тем более все кто мог, уже написал об этом, лучше сходить на митинг, кто в мск.

провокатор

**Comment by j9JMQETa0f** [comment]
Обоснуйте плизик. Как там, кстати, в Берлине норм? :)

**Comment by j9JMQETa0f** [comment]
@loalexandra я конечно проще понаставить дизлайки, но раз взялись, но решите уже может быть наконец автообновление файлика ридми? Вроде три строчки дописать, 5 минут делов, пинганите бэкендэров что ли, стыд и позор какой-то (((

**Comment by koutsenko** [comment]
Почему issue закрыт? По-хорошему те кто руками в README.md записался не нужны - в доке четко сказано что надо создавать файл в /sign/. А README.md это шаблон заполняемый на базе /sign/. Просто нужна автогенерация, как тут пишут - включить Travis.

С уважением, фронтендер))
