### ISSUE TITLE
Отображать количество подписавшихся

### ISSUE THREAD

**Issue by wsbaser** [developers-against-repressions/case-212#981]
Нужно как то считать и отображать в текте письма количество подписавшихся. Просто смотря на табличку уже сложно оценить масштаб. 
Раньше это было видно по количеству контрибьюторов (и это было круто т.к. можно было проверить профили на github), но сейчас насколько я понимаю процесс обновления изменили и количество контрибьюторов застыло на 203 при том что подписавшихся уже более 600.

**Comment by kachkaev** [comment]
Duplicate of https://github.com/developers-against-repressions/case-212/issues/446
